# Generated by Django 3.2.4 on 2021-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_and_audio', '0005_activitypersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
