# Generated by Django 3.2.4 on 2021-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_and_audio', '0006_alter_activitypersession_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitypersession',
            name='count',
        ),
        migrations.AddField(
            model_name='activitypersession',
            name='audio_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitypersession',
            name='overall_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitypersession',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
    ]
