# Generated by Django 3.2.4 on 2021-06-21 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('video_and_audio', '0007_auto_20210620_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypersession',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
