# Generated by Django 3.2.4 on 2021-06-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_and_audio', '0008_alter_activitypersession_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypersession',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
