# Generated by Django 3.2.4 on 2021-06-21 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_and_audio', '0009_alter_activitypersession_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_and_audio.activitypersession'),
        ),
    ]
