# Generated by Django 3.2.4 on 2021-06-21 07:24

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_and_audio', '0011_alter_video_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='mp3',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='audios/', validators=[cloudinary_storage.validators.validate_video]),
        ),
        migrations.AlterField(
            model_name='video',
            name='mp4',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
